### ISSUE TITLE
No access to HIPAA API (https://hipaa-api.jotform.com)

### ISSUE THREAD

**Issue by brucek2** [jotform/jotform-api-php#11]
This library does not appear to support accounts for which HIPAA has been enabled (these accounts need to use a different base URL, such as https://hipaa-api.jotform.com.

I see there is an open PR which would fix this at https://github.com/jotform/jotform-api-php/pull/10, but it appears that no action is being taken.

**Comment by dzhy89** [comment]
@brucek2 hey, this official repo seems abandoned.

You can easily fix that issue in your project right now in this way. Property `baseURL` is public so after creating an JotForm object you might assign any URL.

`$jotformAPI = new JotForm('YOUR API KEY');`
`$jotformAPI->baseURL = 'https://hipaa-api.jotform.com'`
