### ISSUE TITLE
PDF embedded API response.

### ISSUE THREAD

**Issue by Curtis-Stilwell** [jotform/jotform-api-php#5]
This is the API response I am getting using the PDF embedded widget.

```json
{
  "responseCode": 200,
  "resultSet": {
    "offset": 0,
    "limit": 100,
    "count": 1
  },
  "message": "success",
  "content": [
    {
      "id": "325902956889106665",
      "form_id": "53465840236962",
      "ip": "68.185.209.88",
      "created_at": "2015-12-14 06:49:15",
      "status": "ACTIVE",
      "new": "0",
      "flag": "0",
      "updated_at": "2015-12-14 07:05:16",
      "answers": {
        "3": {
          "text": "Please read ",
          "type": "control_widget",
          "answer": "{\"widget_metadata\":{\"type\":\"links\",\"value\":[{\"url\":\"http://www.example.com/sample.pdf\",\"name\":\"sample.pdf\"}]}}"
        }
      }
    }
  ],
  "limit-left": 99974,
  "duration": "19ms"
}
```

As you can see I am getting this value (string value) for the answer key:
```json
"{\"widget_metadata\":{\"type\":\"links\",\"value\":[{\"url\":\"http://www.example.com/sample.pdf\",\"name\":\"sample.pdf\"}]}}"
```

I believe this isn't correct and should instead have a link to the pdf for the answer key just like file upload.
```json
"http://www.example.com/about/sample.pdf" 
```

**Comment by hasansoydabas** [comment]
We don't have any control of third party widgets' return values. I know it's hard to implement generic app with different cases like this. But it's API consumer's responsibility to handle and manipulate for it's own needs the responses from API.

cc: @kenma9123

**Comment by Curtis-Stilwell** [comment]
Thanks for clarifying. This is going to be hard to implement because there is so many different widgets for the field type "control_widget". Is there any chance you can change the field type to "pdf_embedded" just for iOS and Mac users. We can implement a conditional statement that detects Mac users and iOS users so we don't break any third party Apps.

**Comment by kenma9123** [comment]
There is about 5 output types of widgets AFAIK - old and new ones.

1. normal json string ( like configurable list, matrix dynamique)
2. special json string - with `widget_metadata` key identifier.
   - It has two important keys (`type` and `value`) 
   - `type` key can be one of the following that helps formatting the emails and reports
      - `links` - display an output as a link
      - `imagelinks` - display an output as an image with link
      - `htmltext` - display an output as a html string
   - `value` key holds the value you to display, it can be an array of objects or string
     for `links/imagelinks` types - name, url format in json
       - e.g `{name: “Link”, url: “example.com”}`

       - for multiple e.g `[{name: “Link1”, url: “example.com”, {name: “Link2”, url: “example2.com}]`

     for `htmltext` types - This is base64 encoded.
       - e.g `base64_encode(“<div>I’m a string under div tag</div>”)`

    Examples Widgets:  (“Image Picker”, “Upload Image Preview”, “Squire editor”)

3. pure text - sometimes with newlines(`\n`)

4. text + html string - most of them are old widgets

5. pure html string 

You need to configure the APP to read this types of widgets and parse them properly.
